version: 2.0
jobs:
  checkout-code:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: gradle:jdk11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: The First Step
          command: ci/build-app.sh
      - run: ci/unit-test-app.sh
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/libs
          destination: output
workflows:
  version: 2
  two_job_flow:
    jobs:
      - build:
          requires:
          - checkout-code
      - checkout-code